apiVersion: apps/v1
kind: Deployment
metadata:
  name: named-tunnel-k8s
  labels:
    app: named-tunnel-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: named-tunnel-k8s
  template:
    metadata:
      labels:
        app: named-tunnel-k8s
    spec:
      containers:
        - name: argotunnel-sidecar
          # Image from https://hub.docker.com/r/cloudflare/cloudflared
          image: cloudflare/cloudflared:2020.8.2
          command: ["cloudflared", "tunnel", "run"]
           # Change the last argument, tunnel ID, to your tunnel ID
          args: ["-f", "--credentials-file", "/etc/cloudflared/credentials.json", "ef824aef-7557-4b41-a398-4684585177ad"]
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: tunnel-credentials
              mountPath: "/etc/cloudflared"
              readOnly: true
          env:
            - name: TUNNEL_URL
              value: "http://localhost:80"
            - name: NO_AUTOUPDATE
              value: "true"
            - name: TUNNEL_METRICS
              value: "localhost:5000"
        - name: nginx-server
          image: nginx:latest
          command: 
          ports:
            - containerPort: 80
      volumes:
        - name: tunnel-credentials
          secret:
            secretName: tunnel-credentials
            items:
            - key: ef824aef-7557-4b41-a398-4684585177ad.json
              path: credentials.json